# Generated by Django 2.2.4 on 2019-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('bookname', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('qq', models.CharField(max_length=128)),
                ('pic', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
            ],
        ),
    ]
